---
title: SecCore.Com
author: Knut Magne Huglen
email: kmhuglen@outlook.com
description: ''
baseurl: "/"
url: ''
defaults:
- scope:
    path: "/_posts"
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
