---
title: SecCore.Com
author: Knut Magne Huglen
email: kmhuglen@outlook.com
description: ''
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
